version: "3"

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_manager_db
    ports:
      - "3306:3306"
    restart: on-failure

  myadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "3307:80"
    restart: on-failure
    links:
      - mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/task_manager_db
    ports:
      - 8180:8080
    restart: on-failure
    links:
      - mysql
    depends_on:
      - mysql